### ISSUE TITLE
Make an installable package

### ISSUE THREAD

**Issue by Freso** [nolsto/beets-follow#1]
- [x] Move `follow.py` to subdirectory `beetsplug/`. (see https://beets.readthedocs.org/en/latest/dev/plugins.html#writing-plugins)
- [x] Add `__init__.py` to `beetsplug/`.
- [x] Write `setup.py`/"create the project". (https://docs.python.org/2/distutils/setupscript.html, https://packaging.python.org/en/latest/distributing.html)
- [x] Optional: upload to PyPi. (https://packaging.python.org/en/latest/distributing.html#uploading-your-project-to-pypi)

And... I think that should do it. This will allow me to write an AUR package for this as well as for people to install via pip.

**Comment by nolsto** [comment]
All set. Uploaded to PyPi as well. Thanks!

**Comment by Freso** [comment]
Aand... https://aur.archlinux.org/packages/beets-follow-git/ :)
